"""The provider boundary consumed by workflows; fakes need no inheritance."""

from typing import Any, Protocol

JsonObject = dict[str, Any]


class ProviderGateway(Protocol):
    def gh(self, method: str, path: str, **kwargs: Any) -> Any: ...
    def devin(self, method: str, path: str, **kwargs: Any) -> Any: ...
    def create_session(self, payload: JsonObject) -> JsonObject: ...
    def session(self, sid: str) -> JsonObject: ...
    def attachments(self, sid: str) -> Any: ...
    def pr(self, number: int) -> JsonObject: ...
    def comment(self, number: int, body: str, repository: str | None = None) -> JsonObject: ...
    def slack(self, text: str, key: str, channel: str | None = None) -> JsonObject: ...
    def confirm_publication(self, payload: JsonObject, receipt: JsonObject) -> str: ...
