"""Illustrative data only; never eligible for the live evidence gate."""

SHA = "8f3a21c7d9e04b6a1f28563c9a0d7e4b2c681f95"
CHECKS = [
    dict(
        id="services",
        title="Superset services",
        detail="Web server, worker, Redis and Postgres",
        status="passed",
        duration="42s",
        kind="logs",
        content="[DEMO FIXTURE]\nweb: healthy\nworker: ready\nredis: PONG\npostgres: accepting connections",
    ),
    dict(
        id="database",
        title="Database integrity",
        detail="Migrations, metadata and read/write checks",
        status="passed",
        duration="18s",
        kind="logs",
        content="[DEMO FIXTURE]\nMigration at head\nDataset metadata: consistent\nTransaction rollback: successful",
    ),
    dict(
        id="browser",
        title="Critical browser journeys",
        detail="Sign in → query → chart → dashboard",
        status="passed",
        duration="3m 12s",
        kind="screenshot",
        content="Illustrative chart preview only. No Superset browser was executed. Real captures must include candidate SHA, validator session and timestamp.",
    ),
    dict(
        id="tests",
        title="Regression suite",
        detail="20 scenario checks across changed modules",
        status="passed",
        duration="2m 46s",
        kind="tests",
        content="[DEMO FIXTURE]\n20 passed, 0 failed\nChart filter: 8\nDataset metadata: 6\nSQL Lab: 6",
    ),
    dict(
        id="review",
        title="Independent evidence review",
        detail="Human review of the integrated revision",
        status="pending",
        duration="—",
        kind="review",
        content="Inspect the evidence before recording a demo decision. Demo decisions never merge or approve a real release.",
    ),
]
WORKFLOWS = [
    dict(
        id="WF-041",
        issue=142,
        title="Preserve dashboard filter state",
        area="Dashboard",
        status="integrated",
        run="DV-081",
        minutes=18,
    ),
    dict(
        id="WF-042",
        issue=143,
        title="Handle empty query results",
        area="SQL Lab",
        status="integrated",
        run="DV-082",
        minutes=24,
    ),
    dict(
        id="WF-043",
        issue=144,
        title="Repair dataset metadata refresh",
        area="Datasets",
        status="integrated",
        run="DV-083",
        minutes=16,
    ),
    dict(
        id="WF-044",
        issue=145,
        title="Align chart tooltip formatting",
        area="Charts",
        status="integrated",
        run="DV-084",
        minutes=21,
    ),
    dict(
        id="WF-045",
        issue=146,
        title="Update dependency compatibility",
        area="Dependencies",
        status="integrated",
        run="DV-085",
        minutes=31,
    ),
]
